language: node_js
dist: trusty
sudo: required

matrix:
  include:
    - node_js: 12
      env: BROWSER_TEST=true
    - node_js: 10
      env: BROWSER_TEST=true
    - node_js: 8
      env: BROWSER_TEST=true
    - node_js: 6
      env: BROWSER_TEST=false

addons:
  firefox: latest
  apt:
      packages:
      - fluxbox



before_script:
  - |
    if [ "$BROWSER_TEST" == "true" ]; then
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
      sleep 3
      fluxbox >/dev/null 2>&1 &
    fi

script:
  - npm run test
  - |
    if [ "$BROWSER_TEST" == "true" ]; then
      npm run browser-test
    fi
